### PR TITLE
Update data directory paths

### PR DESCRIPTION
**Pull request by dnicolson**
This pull request updates the README to use the data directory path for Sublime Text 3 and later.

### CODE REVIEW

**Comment by rchl** [comment]
I would rather explain to find the path to the directory by running `Preferences: Browse Packages` from the Command Palette since even the updated paths will not always be correct. For example if the user has upgrade from ST3 then the paths will still point to the `Sublime Text 3` directory.

**Comment by dnicolson** [comment]
Feel free to change it, I was mistaken that Sublime Text 3 uses `~/Library/Application Support/Sublime Text`. It's only the application name that became "Sublime Text" in version 3.

**Comment by rchl** [comment]
Sublime Text 4 uses `Sublime Text` unless there already exists `Sublime Text 3` then it i=uses that.

**Comment by rchl** [comment]
dd0cdcb1f993e943f7c7c3a1d995f60c8e710f48

**Pull request merged**
